Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g11, pull requests merged in 2024-09, with the labels that each got.

#19 Feat/question service
  question-service/.dockerignore
  question-service/.gitignore
  question-service/.husky/pre-commit
  question-service/.prettierignore
  question-service/.prettierrc
  question-service/Dockerfile
  question-service/README.md
  question-service/docs/question-service.postman_collection.json
  question-service/package.json
  question-service/pnpm-lock.yaml
  question-service/src/app.ts
  question-service/src/db/mongoClient.ts
  question-service/src/models/types.ts
  question-service/src/routes/questionsController.ts
  question-service/src/routes/userQuestionsController.ts
  question-service/tsconfig.json
Labels: enhancement, High Priority

#18 Feat/4 UI homepage
  docker-compose.yml
  peerprep-fe/.dockerignore
  peerprep-fe/.env
  peerprep-fe/.eslintrc.json
  peerprep-fe/.gitignore
  peerprep-fe/Dockerfile
  peerprep-fe/README.md
  peerprep-fe/components.json
  peerprep-fe/next.config.mjs
  peerprep-fe/package.json
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/postcss.config.mjs
  peerprep-fe/public/favicon.ico
  peerprep-fe/src/app/(main)/components/Filter/FilterBadge.tsx
  peerprep-fe/src/app/(main)/components/Filter/FilterBar.tsx
  peerprep-fe/src/app/(main)/components/Filter/FilterSelect.tsx
  peerprep-fe/src/app/(main)/components/LandingPage.tsx
  peerprep-fe/src/app/(main)/components/LoggedIn.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemDialog.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemRow.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemTable.tsx
  peerprep-fe/src/app/(main)/layout.tsx
  peerprep-fe/src/app/(main)/page.tsx
  peerprep-fe/src/app/layout.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  peerprep-fe/src/components/ui/badge.tsx
  peerprep-fe/src/components/ui/button.tsx
  peerprep-fe/src/components/ui/command.tsx
  peerprep-fe/src/components/ui/dialog.tsx
  peerprep-fe/src/components/ui/input.tsx
  peerprep-fe/src/components/ui/popover.tsx
  peerprep-fe/src/components/ui/select.tsx
  peerprep-fe/src/fonts/GeistMonoVF.woff
  peerprep-fe/src/fonts/GeistVF.woff
  peerprep-fe/src/lib/utils.ts
  peerprep-fe/src/state/useSearchStore.ts
  peerprep-fe/src/styles/globals.css
  peerprep-fe/src/types/types.ts
  peerprep-fe/tailwind.config.ts
  peerprep-fe/tsconfig.json
Labels: enhancement, High Priority

#25 Fix/file casing
  peerprep-fe/src/app/(main)/components/filter/FilterBadge.tsx
  peerprep-fe/src/app/(main)/components/filter/FilterBar.tsx
  peerprep-fe/src/app/(main)/components/filter/FilterSelect.tsx
Labels: bug

#20 Feat/kubernetes init
  .gitignore
  k8s/peerprep-fe.yml
  k8s/question-service.yml
  peerprep-fe/.env
  question-service/src/app.ts
Labels: enhancement

#24 Authentication
  authentication-service/.gitignore
  authentication-service/Dockerfile
  authentication-service/README.md
  authentication-service/controllers/token_login.go
  authentication-service/controllers/user_login.go
  authentication-service/controllers/user_registration.go
  authentication-service/go.mod
  authentication-service/go.sum
  authentication-service/main.go
  authentication-service/models/login_model.go
  authentication-service/models/registration_model.go
  authentication-service/models/user_model.go
  authentication-service/routes/routes.go
  authentication-service/services/db.go
  authentication-service/utils/jwt_utils.go
  authentication-service/utils/password_utils.go
  docs/peerprep.postman_collection.json
  question-service/docs/question-service.postman_collection.json
Labels: enhancement, High Priority

#27 Feat/question service
  docs/peerprep.postman_collection.json
  package.json
  peerprep-fe/src/app/(main)/components/problems/ProblemRow.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemTable.tsx
  peerprep-fe/src/types/types.ts
  question-service/README.md
  question-service/package.json
  question-service/pnpm-lock.yaml
  question-service/src/models/types.ts
  question-service/src/routes/questionsController.ts
  question-service/src/routes/userQuestionsController.ts
Labels: enhancement

#28 revert state to milestone d2
  authentication-service/.gitignore
  authentication-service/Dockerfile
  authentication-service/README.md
  authentication-service/controllers/token_login.go
  authentication-service/controllers/user_login.go
  authentication-service/controllers/user_registration.go
  authentication-service/go.mod
  authentication-service/go.sum
  authentication-service/main.go
  authentication-service/models/login_model.go
  authentication-service/models/registration_model.go
  authentication-service/models/user_model.go
  authentication-service/routes/routes.go
  authentication-service/services/db.go
  authentication-service/utils/jwt_utils.go
  authentication-service/utils/password_utils.go
  docker-compose.yml
  docs/peerprep.postman_collection.json
  k8s/peerprep-fe.yml
  k8s/question-service.yml
  peerprep-fe/.dockerignore
  peerprep-fe/Dockerfile
  question-service/.dockerignore
  question-service/Dockerfile
  question-service/package.json
  question-service/src/models/types.ts
  question-service/src/routes/questionsController.ts
Labels: Chore
