Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g11, pull requests merged in 2024-11, with the labels that each got.

#98 add oauth
  docker-compose.yml
  peerprep-fe/src/app/oauth/callback/page.tsx
  peerprep-fe/src/app/signin/page.tsx
  peerprep-fe/src/app/signup/page.tsx
  peerprep-fe/src/components/ui/loading.tsx
  peerprep-fe/src/lib/oauth.ts
  peerprep-fe/src/middleware.ts
  user-service/controller/oauth-controller.js
  user-service/routes/auth-routes.js
Labels: enhancement

#97 add burst mode to pods
  k8s/peerprep-fe.yml
  k8s/question-service.yml
  k8s/redis-server.yml
  k8s/user-service.yml
Labels: enhancement

#96 Add user profile operations and minor fixes
  api-gateway/Dockerfile
  docker-compose.prod.yml
  docker-compose.yml
  package.json
  peerprep-fe/.dockerignore
  peerprep-fe/package.json
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/src/app/(main)/components/filter/FilterBadge.tsx
  peerprep-fe/src/app/(main)/components/filter/FilterSelect.tsx
  peerprep-fe/src/app/(main)/components/filter/TopicsPopover.tsx
  peerprep-fe/src/app/match/layout.tsx
  peerprep-fe/src/app/match/page.tsx
  peerprep-fe/src/app/profile/layout.tsx
  peerprep-fe/src/app/profile/page.tsx
  peerprep-fe/src/app/signin/page.tsx
  peerprep-fe/src/app/signup/page.tsx
  peerprep-fe/src/components/dialogs/PreMatch.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  peerprep-fe/src/components/ui/card.tsx
  peerprep-fe/src/components/ui/label.tsx
  peerprep-fe/src/lib/constants.ts
  peerprep-fe/src/lib/utils.ts
  peerprep-fe/src/state/useAuthStore.ts
  peerprep-fe/src/types/validation.ts
  pnpm-lock.yaml
  user-service/controller/auth-controller.js
  user-service/pnpm-lock.yaml
  user-service/routes/auth-routes.js
Labels: enhancement, Nice to have

#105 Fix OAuth formatting and requesting
  docker-compose.prod.yml
  docker-compose.yml
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/src/app/match/page.tsx
  peerprep-fe/src/app/oauth/callback/page.tsx
  peerprep-fe/src/lib/oauth.ts
  user-service/controller/oauth-controller.js
  user-service/controller/user-controller.js
Labels: bug

#132 fix middleware route
  peerprep-fe/src/middleware.ts
Labels: bug

#131 Create audio service
  docker-compose.prod.yml
  docker-compose.yml
  peerprep-fe/package.json
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/src/app/collaboration/components/AudioSharing.tsx
  peerprep-fe/src/app/collaboration/components/CollaborationEditor.tsx
  session-service/Dockerfile
  session-service/package.json
  session-service/pnpm-lock.yaml
  session-service/src/audio-service.ts
  session-service/src/server.ts
Labels: enhancement

#133 minor fixes for admin validation
  peerprep-fe/src/app/(main)/components/filter/TopicsPopover.tsx
  peerprep-fe/src/app/admin/page.tsx
  peerprep-fe/src/components/dialogs/ActionDialog.tsx
  peerprep-fe/src/components/problems/ProblemDescriptionPanel.tsx
  peerprep-fe/src/components/problems/ProblemInputDialog.tsx
  peerprep-fe/src/components/problems/ProblemRow.tsx
Labels: bug, enhancement

#168 update home component
  k8s/ingress.yml
  peerprep-fe/src/app/(main)/page.tsx
Labels: Chore

#169 update env for turn
  cloudbuilds/fe.yaml
Labels: bug

#176 Add lazy loading to question fetching
  peerprep-fe/src/app/(main)/components/Main.tsx
  peerprep-fe/src/app/admin/page.tsx
  peerprep-fe/src/app/collaboration/page.tsx
  peerprep-fe/src/components/problems/ProblemRow.tsx
  peerprep-fe/src/components/problems/ProblemTable.tsx
  peerprep-fe/src/hooks/useFilteredProblems.ts
  question-service/src/routes/questionsController.ts
Labels: enhancement
