Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g11, pull requests merged in 2024-10, with the labels that each got.

#37 chore/re-implement K8 and docker
  docker-compose.yml
  k8s/peerprep-fe.yml
  k8s/question-service.yml
  peerprep-fe/.dockerignore
  peerprep-fe/Dockerfile
  question-service/.dockerignore
  question-service/Dockerfile
  question-service/package.json
  question-service/pnpm-lock.yaml
Labels: Chore

#39 Feat/login
  docs/peerprep.postman_collection.json
  peerprep-fe/package.json
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/src/app/(main)/components/LandingPage.tsx
  peerprep-fe/src/app/(main)/page.tsx
  peerprep-fe/src/app/signin/page.tsx
  peerprep-fe/src/app/signup/page.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  peerprep-fe/src/components/ui/alert.tsx
  peerprep-fe/src/components/ui/checkbox.tsx
  peerprep-fe/src/components/ui/dropdown-menu.tsx
  peerprep-fe/src/hooks/useAuth.tsx
Labels: High Priority

#46 Admin Frontend
  peerprep-fe/pnpm-lock.yaml
  peerprep-fe/src/app/(main)/components/Main.tsx
  peerprep-fe/src/app/(main)/components/filter/FilterBar.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemDialog.tsx
  peerprep-fe/src/app/(main)/components/problems/ProblemRow.tsx
  peerprep-fe/src/app/(main)/page.tsx
  peerprep-fe/src/app/admin/layout.tsx
  peerprep-fe/src/app/admin/page.tsx
  peerprep-fe/src/app/signin/page.tsx
  peerprep-fe/src/app/signup/page.tsx
  peerprep-fe/src/components/dialogs/ActionDialog.tsx
  peerprep-fe/src/components/dialogs/InformationDialog.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  peerprep-fe/src/components/problems/ProblemInputDialog.tsx
  peerprep-fe/src/components/problems/ProblemRow.tsx
  peerprep-fe/src/components/problems/ProblemTable.tsx
  peerprep-fe/src/components/ui/textarea.tsx
  peerprep-fe/src/hooks/useFilteredProblems.ts
  peerprep-fe/src/lib/auth.ts
  peerprep-fe/src/lib/constants.ts
  peerprep-fe/src/lib/utils.ts
  peerprep-fe/src/middleware.ts
  peerprep-fe/src/network/axiosClient.ts
  peerprep-fe/src/network/axiosServer.ts
  peerprep-fe/src/state/useAuthStore.ts
  peerprep-fe/src/types/types.ts
  question-service/src/app.ts
  question-service/src/routes/questionsController.ts
  user-service/index.js
Labels: enhancement

#69 Loading Page Skeleton
  peerprep-fe/src/app/(main)/components/filter/FilterBar.tsx
  peerprep-fe/src/app/(main)/match/page.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
Labels: enhancement

#71 Update files
  package.json
  peerprep-fe/src/app/(main)/components/filter/FilterBar.tsx
  peerprep-fe/src/app/(main)/match/page.tsx
  peerprep-fe/src/app/admin/page.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  pnpm-lock.yaml
Labels: bug

#79 Update Admin function navigability
  peerprep-fe/.gitignore
  peerprep-fe/src/app/admin/page.tsx
  peerprep-fe/src/components/dialogs/PreMatch.tsx
  peerprep-fe/src/components/navbar/Navbar.tsx
  peerprep-fe/src/middleware.ts
  peerprep-fe/src/state/useQuestionStore.ts
Labels: bug
